### ISSUE TITLE
Potential Problem with `device_type` initializer

### ISSUE THREAD

**Issue by bdlamprecht** [netbox-community/netbox-docker#114]
## Current Behavior

When I try to add new `device_types` to the `initializers` and restart the container for `netbox`, I get the following error:
```
netbox_1         | django.db.utils.IntegrityError: duplicate key value violates unique constraint "dcim_devicetype_manufacturer_id_model_17948c0c_uniq"
netbox_1         | DETAIL:  Key (manufacturer_id, model)=(1, DCS-7150-S52-CL) already exists.
netbox_1         |
netboxdocker_netbox_1 exited with code 1
```
That manufacturer / model does exist already as it was creating during a previous run of the container.

I'm assuming that is what an `initializer` is supposed to do?
Ensure that certain objects exist and, if not, create them.

This issue is limited to the `060_device_types.py` in `/startup_scripts/`, none of the others exhibit this same behavior.
...

## Expected Behavior

To not error out and crash when a `device_type` already exists.
...

## Debug Information

The output of `docker-compose version`: `1.18.0`
The output of `docker version`: `18.06.0-ce`
The command you used to start the project: `docker-compose up`

The output of `docker-compose logs netbox`:

https://gist.github.com/bdlamprecht/e5d9ede813d80797181829342bb996cb

**Comment by cimnine** [comment]
Can you please post an example of a yaml that triggers this behavior?

**Comment by cimnine** [comment]
I was able to load your `device_types.yml` two times with no problems.

If you already have data in Netbox that matches one of the initializers, that's a complex problem. Because there are no primary keys (i.e. ids) in the initializers, it's not possible to distinguish the entries precisely. That's why _all_ given attributes must match _exactly_ for an object not to be created again.

If there is just a very tiny difference, then Django will try to create a new object. But in your case there is already an object, that is similar, yet not identical, and therefore Django will try to create a new object. But it fails to do so, as some unique constraint is violated, i.e. because the value for 'model' in combination with the given manufacturer already exists.

I've tried to come up with a solution that circumvents this problem. But there is not one-size-fits-all solution and that solution is therefore bound to fail for other use-cases. That's why I will leave the scripts as they are.

If you want to create an initializer that supports your case, you may want to adjust (clones of) the existing initializers.

The Django method, that you need to handle for your case, is [`objects.create_or_update()`][django]. The solution would be to pass just the parameters, that you want to use for identification, as the main arguments, and all the other parameters as `default=`:

```python
device_type, created = DeviceType.objects.get_or_create(params.pop('model'), params.pop('slug'), default=params)
```

[django]: https://docs.djangoproject.com/en/1.10/ref/models/querysets/#django.db.models.query.QuerySet.get_or_create
