### ISSUE TITLE
How do I upgrade to a new version

### ISSUE THREAD

**Issue by joyhu** [netbox-community/netbox-docker#256]
How do I upgrade to a new version

**Comment by cimnine** [comment]
Please use Slack to ask question. Also RTFM: https://github.com/netbox-community/netbox-docker/wiki/Troubleshooting#how-to-upgrade

**Comment by lukasjuhrich** [comment]
To give some feedback, I did „read the fucking manual“ for quite some time and I only found the information concerning the upgrade path via, well, this issue. So thanks @joyhu for asking.

This central information does not belong in „troubleshooting“, because that's the page you only visit when things have gone wrong. So in some sense this is indeed a bug in the documentation.
Would it be possible to include that description (even if only as a link) in the [Getting Started](https://github.com/netbox-community/netbox-docker/wiki/Getting-Started) section?
