### ISSUE TITLE
Wiki: pgsql backup/restore example proposal

### ISSUE THREAD

**Issue by u1735067** [netbox-community/netbox-docker#262]
Hello, 

regarding the backup/restore section of the wiki, I already edited to avoid a possible issue with a missing `-T`: don't try `pg_dump -Fc` without it, I learned today that you won't be able to restore your data 😅
`pg_restore` failed with `
postgresql - pg_restore: [custom archiver] could not read from input file: end of file` in my case; explanation at https://github.com/docker-library/postgres/issues/219#issuecomment-490401351

But I'd also like to propose a more complete example : 
```
cd /path/to/netbox
BACKUP_PATH=backup
BACKUP_DATE=$(date +"%Y-%m-%d_%H.%M.%S")
mkdir -p "${BACKUP_PATH}"
echo "${BACKUP_DATE}"
sudo /usr/local/bin/docker-compose exec -T netbox tar c -zvf - -C /opt/netbox/netbox/media ./ > "${BACKUP_PATH}/${BACKUP_DATE}_media.tgz"
sudo /usr/local/bin/docker-compose exec -T postgres sh -c 'pg_dump -v -Fc -c -U $POSTGRES_USER $POSTGRES_DB' > "${BACKUP_PATH}/${BACKUP_DATE}.pgdump"
```

```
cd /path/to/netbox
docker-compose up -d postgres
sudo /usr/local/bin/docker-compose exec -T postgres sh -c 'pg_restore -v -Fc -cU $POSTGRES_USER -d $POSTGRES_DB' < "${BACKUP_PATH}/${BACKUP_DATE}.pgdump"
docker-compose up -d
sudo /usr/local/bin/docker-compose exec -T netbox tar x -zvf - -C /opt/netbox/netbox/media < "${BACKUP_PATH}/${BACKUP_DATE}_media.tgz"
```
Full restore example: restart PgSQL, load old datas, then start the other services and put back media files.

If that's ok for you.

**Comment by cimnine** [comment]
Thank you for the `-T` fix in the wiki. The missing `-T` was probably also the reason why I initially had done the `docker exec -i $(docker-compose ps -q postgres) ...` hack. Because when providing the `-T` this much shorter command suddenly works:

```bash
gunzip -c db_dump.sql.gz | docker-compose exec -T postgres sh -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
```

About your suggestion: I believe that we should provide the basic knowledge to Docker beginners on how to do backups. But it is my opinion that it is up to each and everyone to decide how he/she likes to organize his/her backups. That's why I believe that just showing the basic commands is enough.

But the wiki is open, so if you think otherwise, feel free to edit it again. Just one thought about your suggested script, though:

I suggest to remove the `sudo` part and replace the explicit path to `/usr/local/bin/docker-compose` with simply `docker-compose`. IMO this would make the script more portable.

**Comment by u1735067** [comment]
I should have had removed `sudo` and the full path yes :)

Maybe this, leaving variables to the viewer, but it is not really different from the existing commands, just:
* grouped by operation and with the postgres up pre-restore
* using gzip instead of bzip2 for media files (they are probably already compressed, don't wast too much CPU on them)
* using pg_dump custom format, natively compressed
* verbose everywhere

### Backup SQL and media files
```
docker-compose exec -T netbox tar c -zvf - -C /opt/netbox/netbox/media ./ > "${BACKUP_PATH}/${BACKUP_DATE}_media.tgz"
docker-compose exec -T postgres sh -c 'pg_dump -v -Fc -U $POSTGRES_USER $POSTGRES_DB' > "${BACKUP_PATH}/${BACKUP_DATE}.pgdump"
```


### Restore SQL (using pg_restore) and media files
> ⚠️ CAUTION, existing data will be removed
```
# Make sure postgres container is up
docker-compose up -d postgres
docker-compose exec -T postgres sh -c 'pg_restore -v -Fc -c -U $POSTGRES_USER -d $POSTGRES_DB' < "${BACKUP_PATH}/${BACKUP_DATE}.pgdump"
docker-compose up -d
docker-compose exec -T netbox tar x -zvf - -C /opt/netbox/netbox/media < "${BACKUP_PATH}/${BACKUP_DATE}_media.tgz"
```

**Comment by cimnine** [comment]
This just popped into my head:

> using gzip instead of bzip2 for media files (they are probably already compressed, don't wast too much CPU on them)

If that's true, you could also just `tar` them, without any compression.

And if you wouldn't mind: Could you edit the respective wiki page to include your commands. I think you pretty much nailed it.
