### ISSUE TITLE
Use local_requirements.txt

### ISSUE THREAD

**Issue by jmanteau** [netbox-community/netbox-docker#278]
## Desired Behavior

Match Netbox behaviour with local_requirements.txt to allow users to keep in a clear way the additionnal packages needed.

https://github.com/netbox-community/netbox/blob/f80eb1606012a15d04d760f3ca0a2be95c4b5b6e/upgrade.sh#L45

## Contrast to Current Behavior

Today, the dockerfile use only the requirements.txt

RUN pip install --prefix="/install" --no-warn-script-location -r /requirements.txt

https://github.com/netbox-community/netbox-docker/blob/d058b7bc934c80876bc3fdf9e13bcb830622a4db/Dockerfile#L35

...

## Changes Required

Add those lines in the DockerFile:

COPY ${NETBOX_PATH}/local_requirements.txt /
RUN pip install --prefix="/install" --no-warn-script-location -r /local_requirements.txt

## Discussion: Benefits and Drawbacks

Cleaner separation for adding custom python packages in the image.

**Comment by cimnine** [comment]
Thank you for your suggestion.

The proper way [to enhance the image is documented in our wiki](https://github.com/netbox-community/netbox-docker/wiki/Build#enhance-the-image).

**Comment by jmanteau** [comment]
I know this wiki part but it still require modification to the build run. I was suggesting to improve the usability for users without to tinker with the build.process. It is easier to just have to modify a configuration file. 
However it is not critical and I get your point.

**Comment by cimnine** [comment]
I fear that this would lead to a situation, where we would not able to help with debugging Docker images. If _our_ image is used as base image, we can at least debug up to that point. But if users build the whole image by themselves, we can't help in any way.

In order to keep up to date user would also have to manage a very custom build job. Whereas there are plenty of Docker build systems out there that support re-building your custom image when the base image changes. (Docker Hub and OpenShift are just two examples of build system that support this.)
