### ISSUE TITLE
Unable to run older version of netbox

### ISSUE THREAD

**Issue by Kani999** [netbox-community/netbox-docker#428]
Hello,
I'm trying to get running netbox-docker in version 2.7.11 of netbox

I'm running the following build as the documentation says.
```
export VERSION=v2.7.1
./build.sh $VERSION
docker-compose up
```

But when docker-compose is starting, the following error in netbox container occurs

## Current Behavior

netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django_rq/views.py", line 12, in <module>
netbox_1         |     from rq.exceptions import NoSuchJobError, UnpickleError
netbox_1         | ImportError: cannot import name 'UnpickleError' from 'rq.exceptions' (/opt/netbox/venv/lib/python3.8/site-packages/rq/exceptions.py)
netbox_1         | ❌ Waited 30s or more for the DB to become ready.

---

## Expected Behavior

Running docker-netbox properly

---

What can I do to fix the error?

**Comment by cimnine** [comment]
Please use the [Discussions](https://github.com/netbox-community/netbox-docker/discussions) to ask questions or otherwise fill in a complete bug report.

In any case, have you checked what version of Netbox Docker you need in order to build & run Netbox 2.7.x? Every release only supports a specific version of Netbox Docker. The current release only supports Netbox 2.10.x. [See our release notes for reference](https://github.com/netbox-community/netbox-docker/releases).

**Comment by Kani999** [comment]
@cimnine - I'm sorry, I'm closing this issue.
I did not read the release changes properly. I just have to use the proper version (tag) to achieve what I need.


Maybe the part in documentation https://github.com/netbox-community/netbox-docker/#use-a-specific-netbox-version should be changed to a proper version.

**Comment by cimnine** [comment]
Thank you for the suggestion. We're moving that specific part to the wiki. Please see if https://github.com/netbox-community/netbox-docker/wiki/Version would have been more helpful and – if not feel – free to improve it :)

**Comment by Kani999** [comment]
@cimnine The wiki page is pretty straightforward. Thank you.
