### ISSUE TITLE
Extend Examples for plugins & logging

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-docker#461]
## Desired Behavior

Given the way we can extend configuration files.  It would be useful to provide some example files for logging and adding plugin configurations.   I will submit a PR & document in the wiki within the relevant sections.

## Contrast to Current Behavior

Users are forced to figure out this on their own.

## Changes Required

New logging.py file in the configuration directory
New plugins.py file in the configuration directory
Update wiki section related to plugins
Update wiki section related to logging
Create wiki section related to extending configurations

## Discussion: Benefits and Drawbacks

Biggest benefit would be to allow our user base to further benefit from netbox-docker with less required learning curves given built in examples.

**Comment by cimnine** [comment]
For now I'd say it would be great to have such examples in the wiki. But I don't see why we should ship those to all users by default.

**Comment by FlorianHeigl** [comment]
@cimnine it would remove a lot of insecurity while adding the first plugins.
currently i.e. usual examples are only snippets for single settings, meaning you never authoritatively know what you should have - what comprises the bigger picture.
delivering a valid example config is a good thing, as is having configuration managed in clear locations (as the `plugins.py` would do from what I'm guessing)

Maybe this helps understanding. Maybe also some personal view can help - just for one plugin (gitlab-export) I'm already well past 10 hours trying to make it work. Not even sure yet if it'll be useful, but i need to try it to know.
There's so many unknowns and incomplete docs/procedures that it's eating up time like crazy and even too many questions to update any existing docs.

Having valid examples shipped does make a large difference - especially since it also enforces their validity.
If they're in the wiki, they'll probably not block a release if sudddenly they become invalid - anything that is part of the source tree has a better effect.

Finally - the impact of clear config and good logging is reasonably well-researched

* http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.220.6745&rep=rep1&type=pdf
* https://homes.cs.washington.edu/~mernst/pubs/inadequate-diagnostics-issta2015.pdf

So, please, if possible, be supportive of not just having examples, but of *including examples*.
