### ISSUE TITLE
vSphere Integrated Containers (VIC) doesn't support mounting directories

### ISSUE THREAD

**Issue by adorsett** [netbox-community/netbox-docker#713]
### Current Behavior

Tried deploying to vSphere Integrated Containers (VIC) using docker-compose.  Received error "Bad request error from portlayer: vSphere Integrated Containers does not support mounting directories as a data volume."

### Expected Behavior

While this is a defect in VIC for failure to handle mounting directories correctly, there could possibly be a different method of copying the data into the proper locations for each container that would be compatible with VIC.  

As you can see this from the below vmware KB article last updated in 2018, this is not a new compatibility issue thus making it unlikely to be resolved.  

[https://kb.vmware.com/s/article/56125](https://kb.vmware.com/s/article/56125)

### Docker Compose Version

docker-compose version 1.29.2, build 5becea4c

### Docker Version

```text
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.25
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          1.5.8
  API version:      1.25 (minimum version 1.19)
  Go version:       go1.8.6
  Git commit:       2c978fea
  Built:            Fri Jun 25 06:06:33 2021
  OS/Arch:          linux/amd64
  Experimental:     true
```

### The git Revision

226d8438de8ff7ef1443fda587805f1af8272ea1

### The git Status

```text
On branch release
Your branch is up to date with 'origin/release'.
```

### Startup Command

docker-compose up

### NetBox Logs

```text
Creating network "netbox-docker_default" with the default driver
Creating volume "netbox-docker_netbox-media-files" with local driver
Creating volume "netbox-docker_netbox-postgres-data" with local driver
Creating volume "netbox-docker_netbox-redis-data" with local driver
Creating netbox-docker_postgres_1    ... done
Creating netbox-docker_redis_1       ... done
Creating netbox-docker_redis-cache_1 ...
Creating netbox-docker_netbox-worker_1       ... error
Creating netbox-docker_netbox-housekeeping_1 ...

Creating netbox-docker_redis-cache_1         ... done

ERROR: for netbox-docker_netbox-housekeeping_1  Cannot create container for service netbox-housekeeping: Bad request error from portlayer: mounting directories as a data volume is not supported.

ERROR: for netbox-worker  Cannot create container for service netbox-worker: Bad request error from portlayer: mounting directories as a data volume is not supported.

ERROR: for netbox-housekeeping  Cannot create container for service netbox-housekeeping: Bad request error from portlayer: mounting directories as a data volume is not supported.
ERROR: Encountered errors while bringing up the project.
```

### Content of docker-compose.override.yml

```yaml
version: '3.4'
services:
  netbox:
    ports:
      - 80:8080
```

**Comment by cimnine** [comment]
> While this is a defect in VIC for failure to handle mounting directories correctly, there could possibly be a different method of copying the data into the proper locations for each container that would be compatible with VIC.

I've not used VIC and have no idea how it works, but persistent volumes of some kind are definitely required to run NetBox. For a basic deployment, our NetBox Docker container does ship all it's default configuration files *in the container*. Most of the mounts in our `docker-compose.yml` are just for convenience. Just the `MEDIA_ROOT` is necessary if your users want to upload pictures and other files.

If VIC at least allows you to mount persistent storage *somewhere* in the container, then you can just adjust the NetBox configuration that we ship with NetBox Docker. You can do this via environment variable: Set the `MEDIA_ROOT` to your writable volume, e.g. `/mnt/media_root`.

Since I understood that you can't just mount a new configuration file and if you need to change configuration parameters that can't be changed via an environment variable, then you [extend the NetBox Docker container](https://github.com/netbox-community/netbox-docker/wiki/Build#enhance-the-image). Something along the lines of:

```Dockerfile
FROM ghcr.io/netbox-community/netbox:v3.1-1.6.0

COPY myconfig.py /etc/netbox/myconfig.py
```

While `myconfig.py` contains the relevant parameters, e.g.:

```py
ADMINS = [
  ['John Doe', 'jdoe@example.com'],
]
```

We can't accommodate for all the non-standard container engines out there. Therefore I'm going to close this issue and ask you to use the GitHub Discussions page or our Slack if you need further help.
