### ISSUE TITLE
Tracking and Deployment of Beta Releases?

### ISSUE THREAD

**Issue by jsenecal** [netbox-community/netbox-docker#804]
### Desired Behavior

It would be useful if the build/deployment scripts would track Beta releases as well as stable releases.

### Contrast to Current Behavior

Current behavior only allows for the latest stable release to be built as well of the latest snapshot from the `develop` branch,

### Required Changes

Adapting the deployment scripts to support "prereleases"

### Discussion: Benefits and Drawbacks

Allows for quicker testing of netbox Beta releases.

**Comment by tobiasge** [comment]
We have jobs running to build and test the pre-releases of Netbox. The images are just no pushed at the moment because the initializers are not compatible with the new version.
If you don't need those the you can build the image yourself with `./build.sh feature` or `PRERELEASE=true ./build-latest.sh`.

**Comment by jsenecal** [comment]
Great, thank you
